#!/usr/bin/env bash

count=0
disconnected="/"
disconnected2="\\"
wireless_connected=""
ethernet_connected=""

while true; do
    if ping -c1 www.github.com &>/dev/null; then
        if (( count < 1 )); then
            ID="$(ip link | awk '/state UP/ {print $2}')"
            ((count++))
        fi
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 20
        else
            echo "$wireless_connected" ; sleep 20
        fi
    else
        echo "$disconnected" ; sleep 0.6
        echo "$disconnected2" ; sleep 0.6
    fi
done
