#!/usr/bin/env bash

NO_VPN_STATUS="輦"
VPN_STATUS="聯"

openvpn=$((pgrep -x openvpn > /dev/null && echo on) || echo off);
vpnagentd=$((pgrep -x vpnagentd > /dev/null && echo on) || echo off);

if [ "$openvpn" == "off" ] && [ "$vpnagentd" == "off" ]; then
    echo "$NO_VPN_STATUS"
    exit 0;
fi

IPINFO=$(curl "https://ip.seeip.org/geoip" 2>/dev/null)
LOC=$(echo $IPINFO | jq ".loc" | tr -d '"')
COUNTRY=$(echo $IPINFO | jq ".country_code" | tr -d '"')
CITY=$(echo $IPINFO | jq ".city" | tr -d '"')
IP=$(echo $IPINFO | jq ".ip" | tr -d '"')

if [ "$COUNTRY" != "null" ]; then
    VPN_STATUS="$VPN_STATUS $COUNTRY"
    [ "$CITY" != "null" ] && VPN_STATUS="$VPN_STATUS,$CITY"
fi

echo "$VPN_STATUS"
