#!/usr/bin/env bash

while true; do
    VPN_STATUS="輦"

    if $(pgrep -x openvpn > /dev/null); then
        VPN_STATUS="聯"
    fi;

    if $(pgrep -x vpnagentd > /dev/null); then
        VPN_STATUS="聯"
    fi;
    
    IPINFO=$(curl "https://ip.seeip.org/geoip" 2>/dev/null)
    LOC=$(echo $IPINFO | jq ".loc" | tr -d '"')
    COUNTRY=$(echo $IPINFO | jq ".country_code" | tr -d '"')
    CITY=$(echo $IPINFO | jq ".city" | tr -d '"')
    IP=$(echo $IPINFO | jq ".ip" | tr -d '"')

    echo "$VPN_STATUS $IP ($COUNTRY,$CITY)"
    sleep 10
done;

#return 0;
