#!/bin/env bash

used=$(free -h | sed -n '2p' | awk -F' ' '{print $3}')
used_int=$(echo "$used" | sed "s/\([0-9.]\+\)[a-zA-Z]\+/\1/g")
used_units=$(echo "$used" | sed "s/[0-9.]\+\([a-zA-Z]\+\)/\1/g")

total=$(free -h | sed -n '2p' | awk -F' ' '{print $2}')
total_int=$(echo "$total" | sed "s/\([0-9.]\+\)[a-zA-Z]\+/\1/g")
total_units=$(echo "$total" | sed "s/[0-9.]\+\([a-zA-Z]\+\)/\1/g")

[ "$total_units" == "Gi" ] && [ "$used_units" == "Mi" ] && used_int=$(awk "BEGIN {print $used_int/1000}")

percentage=$(awk "BEGIN {print int($used_int*100/$total_int)}")

if [[ $percentage -gt 80 ]]; then
    icon="<span rise='8000' size='larger' foreground='#FF3333'></span> "
elif [[ $percentage -gt 60 ]]; then
    icon="<span rise='8000' size='larger' foreground='#FF6E33'></span> "
elif [[ $percentage -gt 40 ]]; then
    icon="<span rise='8000' size='larger' foreground='#FFAE33'></span> "
elif [[ $percentage -gt 20 ]]; then
    icon="<span rise='8000' size='larger' foreground='#DEFF33'></span> "
elif [[ $percentage -le 20 ]]; then
    icon="<span rise='8000' size='larger' foreground='#40FF33'></span> "
fi

echo "<span font='9' rise='10000'>$icon<span size='smaller' weight='bold' foreground='#FFFFFF'>${used_int} / ${total_int}</span></span>"
