#!/bin/bash

tempreture=$(sensors | grep "Core" | grep -o -E "[\+\-]?[0-9]*.[0-9]*°C" | sed -n '1p' | tr -d '+°C' | sed 's/^\([0-9]\+\).[0-9]\+/\1/g')
if [[ $tempreture -gt 80 ]]; then
    icon="<span rise='8000' size='larger' foreground='#FF3333'></span> "
elif [[ $tempreture -gt 70 ]]; then
    icon="<span rise='8000' size='larger' foreground='#FF6E33'></span> "
elif [[ $tempreture -gt 60 ]]; then
    icon="<span rise='8000' size='larger' foreground='#FFAE33'></span> "
elif [[ $tempreture -gt 50 ]]; then
    icon="<span rise='8000' size='larger' foreground='#DEFF33'></span> "
elif [[ $tempreture -le 50 ]]; then
    icon="<span rise='8000' size='larger' foreground='#40FF33'></span> "
fi

echo "<span font='9' rise='10000'>$icon<span size='smaller' weight='bold' foreground='#FFFFFF'>$tempreture°C</span></span>"

case $BLOCK_BUTTON in
    1) i3-msg exec sense ;; #lm_sensors
esac
