# ~/.config/starship.toml

# Use custom format
# https://github.com/kentcdodds/advanced-react-patterns
format = """
$directory$character"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the newline at the start of the prompt
add_newline = false

[aws]
format = "[$symbol](bold #ffa500)[$region](bold white) "
symbol = "  "

[nodejs]
format = "[$symbol](bold #3c873a)[$version](bold white) "
symbol = " "

[python]
format = "[$symbol](bold #ffe873)[$version](bold white) "
symbol = " "

# [package]
# format = "[$symbol](bold white)[$version](bold white) "
# symbok = "📦 "

[terraform]
format = "[$symbol](bold #aa47ff)[$version](bold white) "
symbol = " "

# prompt_order = [
#     "username",
#     "hostname",
#     "directory",
#     "package",
#     "memory_usage",
#     "cmd_duration",
#     "character",
# ]

# set SPACEFISH_TIME_SHOW true
# set SPACEFISH_EXIT_CODE_SHOW true
# set SPACEFISH_EXIT_CODE_SYMBOL "✘ "
# set SPACEFISH_EXEC_TIME_COLOR "yellow"
# set SPACEFISH_EXEC_TIME_ELAPSED 1
# set SPACEFISH_JOBS_SYMBOL "華"
# set SPACEFISH_JOBS_COLOR "red"
# set SPACEFISH_DIR_TRUNC 3
# set SPACEFISH_DIR_COLOR white
# set SPACEFISH_DIR_TRUNC_REPO true
# set SPACEFISH_PROMPT_PREFIXES_SHOW false
# set SPACEFISH_HOST_COLOR_SSH "FFBD55"
# set SPACEFISH_HOST_COLOR "FFBD55"
# set SPACEFISH_USER_COLOR "FF6155"
# set SPACEFISH_USER_COLOR_ROOT "FF6155"
# set SPACEFISH_GIT_BRANCH_COLOR brblack
# set SPACEFISH_GIT_STATUS_COLOR brblack
# set SPACEFISH_AWS_SYMBOL " "
# set SPACEFISH_AWS_COLOR "white"
# set SPACEFISH_PROMPT_ADD_NEWLINE false
# set SPACEFISH_JOBS_AMOUNT_THRESHOLD 0
# set SPACEFISH_VI_MODE_INSERT "❯"
# set SPACEFISH_VI_MODE_NORMAL "❮"
# set SPACEFISH_VI_MODE_VISUAL "V"
# set SPACEFISH_VI_MODE_REPLACE_ONE "^"
# set SPACEFISH_VI_MODE_COLOR "0BB087"
# set SPACEFISH_PROMPT_ORDER user host dir vi_mode
# set SPACEFISH_RPROMPT_ORDER git jobs aws exec_time exit_code
# set ASK_DEFAULT_DEVICE_LOCALE "en-US"
#set -x AWS_PROFILE default # Override in session to use another profile
